#!/bin/sh
in_termux() {
  type termux-setup-storage 2>&1 >/dev/null
}
previm_path=/sdcard/previm
cd "$(dirname "$0")"
find home -type f |
  xargs -I% sh -c 'echo "%" | sed "s:^home/::"' |
  xargs -I% sh -c 'mkdir -pv "$HOME/$(dirname "%")" && ln -fsv "$PWD/home/%" "$HOME/%"'
touch ~/.aliases.local
touch ~/.config/nvim/lua/init_local.lua
touch ~/.config/nvim/tasks_local.ini
touch ~/.gitconfig.local
touch ~/.zaliases.local
touch ~/.zshrc.local
if in_termux && [ ! -d "$previm_path" ]; then
  git clone --depth=1 -b latest https://github.com/sakkke/previm "$previm_path"
fi
